WebStore/WebStore/Controllers/ShoppingWishListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStore.Models.Cart;
using WebStore.Models.DataBase;
using WebStore.ViewModels;

namespace WebStore.Controllers
{
    public class ShoppingWishListController : Controller
    {
        StoreItemsEntities storeItemsDb = new StoreItemsEntities();

        [Authorize]
        public ActionResult Index()
        {
            var wishList = ShoppingWishList.GetWishList(this.HttpContext);


            var viewModel = new ShoppingWishListViewModel
            {
                WishListItems = wishList.GetWishListItems(),
                WishListTotal = wishList.GetTotal()
            };
            return PartialView(viewModel);
        }

        [Authorize]
        public ActionResult AddToWishList(int id)
        {
            if(!storeItemsDb.Items
                .Any(item => item.ItemId == id))
            {
                return View("Error");
            }

            var addedItem = storeItemsDb.Items
                .Single(item => item.ItemId == id);

            var wishList = ShoppingWishList.GetWishList(this.HttpContext);

            wishList.AddToWishList(addedItem);

            return RedirectToAction("Index", "ShoppingCart");
        }

        [Authorize]
        [HttpPost]
        public ActionResult RemoveFromWishList(int id)//id na liście WL
        {
            var wishList = ShoppingWishList.GetWishList(this.HttpContext);
            string itemName = storeItemsDb.WishLists
                .Single(item => item.RecordId == id).Item.Title;
            
            int itemCount = wishList.RemoveFromWishList(id);

            var results = new ShoppingWishListRemoveViewModel
            {
                Message = itemName +
                    " has been removed from your wish list.",
                WishListTotal = wishList.GetTotal(),
                WishListCount = wishList.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }


        [ChildActionOnly]
        public ActionResult WishListSummary()
        {
            var wishList = ShoppingWishList.GetWishList(this.HttpContext);

            ViewBag.WishListCount = wishList.GetCount();
            return PartialView("WishListSummary");
        }

        public ActionResult MoveToCart(int id)//id itemu
        {
            var dbItem = storeItemsDb.Items.Where(x => x.ItemId == id).SingleOrDefault();
            if (dbItem != null && dbItem.IsReserved==false)
            {

                var wishList = ShoppingWishList.GetWishList(this.HttpContext);
                var cart = ShoppingCart.GetCart(this.HttpContext);

                cart.AddToCart(dbItem);
                wishList.RemoveFromWishList(wishList.GetWishListItems().Single(x => x.ItemId == id).RecordId);

                storeItemsDb.SaveChanges();
                return RedirectToAction("Index", "ShoppingCart");
            }
            return View("Error");
        }
    }
}

WebStore/WebStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStore.Models;
using WebStore.Models.Cart;
using WebStore.Models.DataBase;

namespace WebStore.Controllers
{
    public class StoreController : Controller
    {
        StoreItemsEntities storeItemsDb = new StoreItemsEntities();


        public ActionResult Browse(string category)
        {

            ViewBag.ReturnUrl = HttpContext.Request.RawUrl;

            var categoryModel = storeItemsDb.Categories.Include("Items")
                .SingleOrDefault(g => g.Name == category);

            return categoryModel==null ? View("Error") : View(categoryModel);
        }

        public ActionResult Details(int id)
        {
            ShoppingCart.TimeExpiresCheck();
            ViewBag.ReturnUrl = HttpContext.Request.RawUrl;
            var item = storeItemsDb.Items.Find(id);

            if (item == null) return View("Error");

            ViewBag.IsReserved = item.IsReserved;
            return View(item);
        }

        [ChildActionOnly]
        public ActionResult CategoryMenu()
        {
            var categories = storeItemsDb.Categories.ToList();
            return PartialView(categories);
        }

        public ActionResult Index(string itemCategory, string searchString)
        {
            var categoryList = new List<string>();

            var categoryQuery = storeItemsDb.Categories.OrderBy(d => d.Name).Distinct().Select(d => d.Name);

            categoryList.AddRange(categoryQuery);
            ViewBag.itemCategory = new SelectList(categoryList);

            var items = storeItemsDb.Items.Select(m => m).ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                items = items.Where(s => s.Title.ToLowerInvariant().Contains(searchString.ToLowerInvariant()) ).ToList();
               // items.Where(s => s.Title.Contains())
            }

            if (string.IsNullOrEmpty(itemCategory))
            {
                return View(items);
            }
            else
            {
                return View(items.Where(x => x.Category.Name == itemCategory));
            }

        }


    }
}

WebStore/WebStore/Views/Store/Browse.cshtml
@using WebStore.Models
@model WebStore.Models.Category
 
@{
    ViewBag.Title = "Browse Items";
}
 
<div class="category">
    <h3><em>@Model.Name</em> Items</h3>
    @ItemList(Model.Items)
</div>

@helper ItemList(IEnumerable<Item> items)
{
    <ul id="item-list">
        @foreach (var item in items)
        {
            <li>
                <a href="@Url.Action("Details", "Store", new { id = item.ItemId })">
                    <img alt="@item.Title" src="@item.ItemArtUrl" />
                    <span>@item.Title</span>
                </a>
            </li>
        }
    </ul>    
}

WebStore/WebStore/Views/Store/CategoryMenu.cshtml
@model IEnumerable<WebStore.Models.Category>
<ul id="categories">
    @foreach (var category in Model)
    {
        <li>
            @Html.ActionLink(category.Name, "Browse", "Store", new { Category = category.Name }, null)
        </li>
    }
</ul>

WebStore/WebStore/Views/Store/Details.cshtml
@model WebStore.Models.Item
@{
    ViewBag.Title = "Item - " + Model.Title;
 }
<h2>@Model.Title</h2>
<p>
    <img alt="@Model.Title" src="@Model.ItemArtUrl" />
</p>
<div id="item-details">
    <p>
        <em>Category:</em>
        @Model.Category.Name
    </p>
    <p>
        <em>SubCategory:</em>
        @Model.SubCategory.Name
    </p>
    <p>
        <em>Price:</em>
        @String.Format("{0:F}", Model.Price)
    </p>

    @if (!ViewBag.IsReserved)
    {
        <p class="button">
            @Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new {id = Model.ItemId}, "")
        </p>
    }

    <p class="button">
        @Html.ActionLink("Add to wish list", "AddToWishList",  "ShoppingWishList", new { id = Model.ItemId }, "")
    </p>
</div>

WebStore/WebStore/Views/Store/Index.cshtml
@using WebStore.Models
@model IEnumerable<WebStore.Models.Item>

@{
    ViewBag.Title = "Index";
}

<h3>Search items:</h3>
<p>
    @using (Html.BeginForm()){   
         <p>Category: @Html.DropDownList("itemCategory", "All")  
        &nbsp;  Title: @Html.TextBox("SearchString")  
         <input type="submit" value="Filter" /></p>
        }
</p>
<ul>
    @ItemList(Model)
</ul>

@helper ItemList(IEnumerable<Item> items)
{
    <ul id="item-list">
        @foreach (var item in items)
        {
            <li>
                <a href="@Url.Action("Details", "Store", new { id = item.ItemId })">
                    <img alt="@item.Title" src="@item.ItemArtUrl" />
                    <span>@item.Title</span>
                </a>
            </li>
        }
    </ul>    
}